pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "maven"
    }

    stages {
        stage('Gitcheckout') {
            steps {
checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'mygit_cred', url: 'https://github.com/caithan/basicpipelinepro.git']]])            }
        }
        stage('build') {
            steps {
              bat 'mvn clean install' -f java-hello-world-with-maven-master/pom.xml
            }
        }
        stage('codeQuality') {
            steps {
               bat 'mvn sonar:sonar' -f java-hello-world-with-maven-master/pom.xml            
            }
        }
        stage('deploy') {
            steps {
deploy adapters: [tomcat9(credentialsId: 'tomcat_robot', path: '', url: 'http://localhost:7000/')], contextPath: 'basicpipelinepro/java-hello-world-with-maven-master', war: '**/*.war'   }
    }
    }}

